import { BiodataFormData } from "@/lib/types/biodata";

export const SAMPLE_BIODATA: BiodataFormData = {
  personalDetails: {
    fullName: "Priya Sharma",
    dateOfBirth: "1998-03-15",
    timeOfBirth: "10:30 AM",
    placeOfBirth: "Jaipur, Rajasthan",
    height: "5.4",
    weight: "55",
    bloodGroup: "B+",
    complexion: "Fair",
    bodyType: "Slim",
    manglikStatus: "Non-Manglik",
    gotra: "Bharadwaj",
    religion: "Hindu",
    caste: "Brahmin",
    subCaste: "Gaur",
    motherTongue: "Hindi",
    languagesKnown: ["Hindi", "English", "Marwari"],
    nationality: "Indian",
    currentCity: "Bangalore",
    currentState: "Karnataka",
  },
  educationCareer: {
    highestEducation: "B.Tech (Computer Science)",
    educationDetails: "IIT Delhi, 2020",
    occupation: "Software Engineer",
    jobTitle: "Senior Software Engineer",
    companyName: "Google India",
    workLocation: "Bangalore",
    annualIncome: "25-30 LPA",
  },
  familyDetails: {
    fatherName: "Sh. Rajesh Sharma",
    fatherOccupation: "Retired Bank Manager",
    motherName: "Smt. Sunita Sharma",
    motherOccupation: "Homemaker",
    brothers: 1,
    brothersMarried: 0,
    sisters: 1,
    sistersMarried: 1,
    familyType: "Nuclear",
    familyStatus: "Middle Class",
    familyValues: "Moderate",
    nativePlace: "Jaipur, Rajasthan",
  },
  lifestyle: {
    diet: "Vegetarian",
    smoking: "No",
    drinking: "No",
    hobbies: ["Reading", "Yoga", "Painting", "Travel"],
    aboutMe:
      "A family-oriented person with a passion for technology and creativity. I believe in maintaining a balance between career and personal life.",
  },
  partnerPreferences: {
    preferredAgeMin: 27,
    preferredAgeMax: 32,
    preferredHeightMin: "5.6",
    preferredHeightMax: "6.2",
    preferredEducation: "Graduate or above",
    preferredOccupation: "Professional",
    preferredLocation: "Metro cities",
    preferredDiet: "Vegetarian",
    preferredManglik: "Non-Manglik",
  },
  contactDetails: {
    contactPersonName: "Sh. Rajesh Sharma",
    contactRelation: "Father",
    phone: "9876543210",
    email: "sharma.family@email.com",
    whatsapp: "9876543210",
    address: "A-12, Malviya Nagar, Jaipur, Rajasthan",
    showPhone: true,
    showEmail: true,
    showAddress: true,
    showWhatsapp: true,
  },
  horoscope: {
    rashi: "Meen (Pisces)",
    nakshatra: "Revati",
    charan: "3",
    gan: "Dev",
    nadi: "Adi",
  },
};
